DROP TABLE IF EXISTS Users;

-- Crear tabla
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password char(60) NOT NULL
);
/* 
-- insertar datos para probar
INSERT INTO users (name, last_name, correo) VALUES
('John', 'Doe', 'john.doe@example.com'),
('Jane', 'Doe', 'jane.doe@example.com'),
('Bob', 'Smith', 'bob.smith@example.com'),
('Alice', 'Johnson', 'alice.johnson@example.com'),
('Michael', 'Williams', 'michael.williams@example.com'),
('Emily', 'Brown', 'emily.brown@example.com'),
('Daniel', 'Garcia', 'daniel.garcia@example.com'),
('Olivia', 'Davis', 'olivia.davis@example.com'),
('Lucas', 'Miller', 'lucas.miller@example.com'),
('Isabella', 'Wilson', 'isabella.wilson@example.com'),
('Matthew', 'Moore', 'matthew.moore@example.com'),
('Sophia', 'Taylor', 'sophia.taylor@example.com'),
('David', 'Anderson', 'david.anderson@example.com'),
('Ava', 'Thomas', 'ava.thomas@example.com'),
('Christopher', 'Jackson', 'christopher.jackson@example.com'),
('Madison', 'White', 'madison.white@example.com'),
('Benjamin', 'Harris', 'benjamin.harris@example.com'),
('Chloe', 'Martin', 'chloe.martin@example.com'),
('William', 'Thompson', 'william.thompson@example.com'),
('Ella', 'Garcia', 'ella.garcia@example.com'),
('Andrew', 'Martinez', 'andrew.martinez@example.com'),
('Victoria', 'Davis', 'victoria.davis@example.com'),
('Joseph', 'Anderson', 'joseph.anderson@example.com'),
('Grace', 'Rodriguez', 'grace.rodriguez@example.com'),
('Ryan', 'Lewis', 'ryan.lewis@example.com'),
('Lily', 'Lee', 'lily.lee@example.com'),
('Nicholas', 'Walker', 'nicholas.walker@example.com'),
('Hannah', 'Hall', 'hannah.hall@example.com'),
('Ethan', 'Young', 'ethan.young@example.com'),
('Natalie', 'Allen', 'natalie.allen@example.com'),
('Jacob', 'King', 'jacob.king@example.com'),
('Avery', 'Wright', 'avery.wright@example.com'),
('Tyler', 'Lopez', 'tyler.lopez@example.com'),
('Evelyn', 'Hill', 'evelyn.hill@example.com'),
('Mason', 'Scott', 'mason.scott@example.com'),
('Mia', 'Green', 'mia.green@example.com'),
('Alexander', 'Baker', 'alexander.baker@example.com'),
('Aria', 'Adams', 'aria.adams@example.com'),
('Luke', 'Campbell', 'luke.campbell@example.com'),
('Scarlett', 'Parker', 'scarlett.parker@example.com'),
('Caleb', 'Evans', 'caleb.evans@example.com'),
('Leah', 'Edwards', 'leah.edwards@example.com'),
('Julian', 'Collins', 'julian.collins@example.com'),
('Audrey', 'Stewart', 'audrey.stewart@example.com'); */