services:
  client:
    build:
      context: 'client'
    ports:
      - '5173:80'
    networks:
      - client-side
  server:
    environment:
      - NODE_ENV=docker
      - DATABASE_HOST=db
      - DATABASE_PWD=mysecretpassword
    build:
      context: 'server'
    ports:
      - '3000:3000'
    depends_on:
        - db
    networks:
        - client-side
        - server-side
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    networks:
        - server-side

networks:
  client-side: {}
  server-side: {}

volumes:
  data: {}